name: Node.js Express with Helmet
version: 0.4.1
description: Express web framework for Node.js
license: Apache-2.0
language: nodejs
maintainers:
  - name: Ivan Molina
    email: Fiserv.com
    github-id: fiserv-imolina
default-template: simple
requirements:
  docker-version: ">= 17.09.0"
  appsody-version: ">= 0.2.7"
